<WelcomePage>:
    orientation: "vertical"

    Label:
        id: name_label
        size_hint_y: 0.3
        text: "Wordle"
        font_size: 50

    Button:
        size_hint_y: 0.15
        id: play_button
        text: "Play"
        on_press:root.switch_to_game_page(self)

    Button:
        size_hint_y: 0.15
        id: settings_button
        text: "Settings"
        on_press:root.switch_to_settings_page(self)

<OverPage>:
    orientation: "vertical"

    Label:
        id: name_label
        size_hint_y: 0.3
        font_size: 30

    Button:
        size_hint_y: 0.15
        id: play_button
        text: "Play"
        on_press:root.switch_to_game_page(self)

    Button:
        size_hint_y: 0.15
        id: home_button
        text: "Home"
        on_press:root.switch_to_welcome_page(self)

<SettingsPage>:
    orientation: "vertical"

    Label:
        id: name_label
        size_hint_y: 0.3
        text: "Settings"
        font_size: 30

    Button:
        size_hint_y: 0.15
        id: play_button
        text: "Sound ON"
        on_press:root.switch_sound()

    Button:
        size_hint_y: 0.15
        id: settings_button
        text: "Home"
        on_press:root.switch_to_welcome_page()


<GamePage>:
    orientation: "vertical"

    Label:
        size_hint_y: 0.3
        id: result_label
        markup: True

    Label:
        size_hint_y: 0.15
        id: words_label

    Button:
        size_hint_y: 0.15
        id: submit_button
        text: "Submit Guess"
        on_press: root.check_guess(self)

    BoxLayout:
        id: keyboard_layout
        orientation: "vertical"
        size_hint_y: 0.4

        padding: 10
        spacing: 5
