<WordleLayout>:
    orientation: "vertical"

    Label:
        id: result_label
        markup: True

    Label:
        id: words_label
        markup: True

    Button:
        id: submit_button
        text: "Submit Guess"
        on_press: root.check_guess(self)

    LimitedTextInput:
        id: input_box
        multiline: False
        hint_text: "Enter your guess (5 letters)"
        on_text_validate: root.check_guess(self)
